version: "3.7"
name: gen_2_team_8_services
services:
  
  gen_2_team_8_api:
    build: .
    image: gen_2_team_8_api_image
    container_name: gen_2_team_8_api_container
    ports:
      - "800#:800#"
    links:
      - gen_2_team_8_postgres_app
    env_file:
      - .env


  gen_2_team_8_postgres_app:
    image: postgres
    container_name: gen_2_team_8_postgres_container
    ports: 
      - "543#:5432"
    env_file:
      - .env.db.docker
    volumes:
      - gen_2_team_8_postgres_volume:/var/lib/postgresql/data

volumes:
  gen_2_team_8_postgres_volume: